project_id = "fbxtflpiszcqgveckyjm"

[functions.import-numbers]
verify_jwt = true

[functions.send-authorization-email]
verify_jwt = true

[functions.send-order-email]
verify_jwt = true

[functions.yeti-api]
verify_jwt = false

[functions.yeti-admin-api]
verify_jwt = false
